; This is the roster of allowed units for the player in the campaign - this is built off real units that were in the Pacific in June 1985
; Task Force Builder will check this file first to ensure the unit is an allowed unit, then filter further down if the mission has an allowlist

; unit short descriptions (gameplay focused) are now handled per-unit/per-language in unit_roster_descriptions_<lang>.ini


[AllowedVessels]
; syntax is: <unit_type>=<variant_number>,<variant_number>,<variant_number>|<points_cost>

usn_dd_gearing=Variant9,Variant10,Variant18
usn_ff_garcia=Variant2,Variant7,Variant9
usn_ffg_brooke=Variant1,Variant2,Variant3
usn_ff_knox=Variant1,Variant3,Variant14
usn_ff_knox_84=Variant9,Variant13,Variant16,Variant18,Variant20,Variant22,Variant23,Variant25,Variant32,Variant36
usn_ffg_oliver_hazard_perry=Variant17,Variant19
usn_ffg_oliver_hazard_perry_longhull=Variant7,Variant15
usn_ddg_adams_early=Variant12
usn_ddg_adams_late=Variant6,Variant7,Variant8
usn_ddg_coontz=Variant7,Variant10
usn_ddg_mahan=Variant1
usn_dd_spruance=Variant2,Variant3,Variant5,Variant18,Variant29
usn_dd_spruance_abl=Variant2,Variant5
usn_ddg_kidd=Variant3,Variant4
usn_cg_belknap=Variant4,Variant5,Variant7
usn_cg_leahy=Variant3,Variant7,Variant8
usn_clg_oklahoma_city=Variant3
usn_cgn_california=Variant1
usn_cgn_virginia=Variant2
usn_cgn_long_beach_83=Variant1
usn_cg_ticonderoga=Variant4
usn_cgn_alaska=Variant1
usn_bb_iowa=Variant3
usn_lha_tarawa=Variant5
usn_cv_kitty_hawk=Variant1,Variant2

usn_avp_barnegat_mod=Variant1,Variant2,Variant3,Variant4

ran_ddg_perth=Variant1,Variant2,Variant3
ran_ffg_adelaide_shorthull=Variant1,Variant2,Variant3

jmsdf_dd_yamagumo=Variant1,Variant2,Variant3,Variant4,Variant5,Variant6
jmsdf_dd_minegumo=Variant1,Variant2,Variant3
jmsdf_dd_takatsuki=Variant1,Variant2,Variant3,Variant4
jmsdf_ddg_tachikaze=Variant1,Variant2,Variant3
jmsdf_ddh_haruna=Variant1,Variant2



[AllowedSubmarines]
; Note: subs are currently not available for purchase in Pacific Strike campaign due to mission-level allowlisting removing them.
; syntax is: <unit_type>=<variant_number>,<variant_number>,<variant_number>|<points_cost>

usn_ssn_permit=Variant3,Variant10,Variant13,Variant9
usn_ssn_sturgeon=Variant28,Variant35,Variant23
usn_ssn_los_angeles=Variant26,Variant31

ran_ss_oberon=Variant3,Variant4

jmsdf_ss_asashio=Variant1,Variant2,Variant3,Variant4
jmsdf_ss_yushio=Variant1,Variant2,Variant3,Variant4,Variant5,Variant6,Variant7,Variant8,Variant9,Variant10
jmsdf_ss_uzushio=Variant1,Variant2,Variant3,Variant4,Variant5,Variant6,Variant7

[LoadoutPrices]
; syntax is: <unit_type>=<loadout_name>,<points_cost>|<loadout_name>,<points_cost>
; aircraft loadouts are included in the aircraft purchase cost


[AllowedHelicopters]
; syntax for aircraft is: <unit_type>=<squadron_number>,<squadron_number>|<points_cost_per_aircraft>

usn_qh-50d=Squadron2
usn_sh-2f=Squadron4,Squadron6,Squadron8
usn_sh-3h=Squadron1
jmsdf_hss-2=Squadron1
fr_alouette_II=Squadron10
usmc_ah-1t=Squadron2
fr_as-350=Squadron1


[AllowedAircraft]
; syntax for aircraft is: <unit_type>=<squadron_number>,<squadron_number>|<points_cost_per_aircraft>

#Fighter
fr_mirage_iii=Squadron2
usmc_av-8a=Squadron3
usaf_f-5a=Squadron11
usaf_f-5e=Squadron14,Squadron18
jasdf_f-4ej=Squadron1,Squadron3,Squadron4
usaf_f-4e=Squadron10
usaf_f-15c=Squadron9
usn_f-14a=Squadron9
usn_fa-18a=Squadron7,Squadron8
#Attack
ran_a-4g=Squadron2
usn_a-7e=Squadron10
usn_a-6e=Squadron3
#Bomber
jasdf_f-1=Squadron2
raaf_f-111c=Squadron2
#Strategic Bomber
usaf_b-52g=Squadron2
#AEW
usn_e-2c=Squadron2
usaf_e-3a=Squadron2
#EW
usn_ea-6b=Squadron6
#MPA
jmsdf_ps-1=Squadron1
jmsdf_us-1=Squadron1
usn_s-3a=Squadron3
usn_p-3c=Squadron14,Squadron29,Squadron31
