
[Debug]
DisableEnemyAIPlayer=True
[ ============================== Languages ============================== ]
[Language_ja]
Name=テキサスに手を出すな (レッドサイド)
Description=米軍は、地域同盟国との「合同演習」を名目に、USSテキサスおよびUSSバージニアを地中海へと配備した。諜報によれば、このいわゆる訓練は我が国近海で米海軍の威容を誇示するための口実に過ぎず、断じて看過できるものではない。シリア沿岸防衛軍の指揮官として、貴官の任務は領海へのいかなる侵入も監視し、防衛することである。緊張は極限まで高まっており、国境線のすぐ外側に位置する米軍艦艇は、シリアの主権に対する重大な脅威となっている。沿岸ミサイル陣地、哨戒艇、および防空部隊は最高レベルの警戒態勢にあり、米艦隊がシリア領海へ侵入、あるいは何らかの挑発行動に出た場合には即座に対応する準備を整えている。不必要なエスカレーションを避けるため慎重を期すべきだが、もしアメリカ軍が増長して我が領土を侵すならば、持てる全火力をもってこれを排除せよ。本任務の成否は、警戒と自制の微妙なバランスを保ちつつ、いかにシリアの不退転の決意を示せるかにかかっている。世界が注視している。シリアは決して屈しないという意志を突きつけるのは、貴官の双肩にかかっている。]
[Language_en]
Name=Don't Mess With Texas (Red Side)
Description=U.S. forces have deployed the USS Texas and USS Virginia to the Mediterranean under the guise of "joint exercises" with regional allies. Intelligence suggests this so-called training is a pretext for demonstrating U.S. naval strength close to our waters, an action we cannot ignore. As the commander of Syrian coastal defense forces, your mission is to monitor and defend against any intrusion into our territorial waters. Tensions are high, and American warships are stationed just outside our borders, posing a serious risk to Syrian sovereignty. Coastal missile sites, patrol boats, and air defense units are on high alert, prepared to respond swiftly should the U.S. fleet cross into Syrian waters or take any provocative actions. Exercise caution to avoid needless escalation, but remain ready to defend our territory if the Americans push their luck. The success of this mission depends on your ability to demonstrate Syria's resolve while navigating the delicate balance between vigilance and restraint. The world is watching, and it’s up to you to send a message that Syria will not back down.
[Language_fr]
Name=Ne vous frottez pas au Texas (Côté rouge)
Description=Les forces américaines ont déployé l'USS Texas et l'USS Virginia en Méditerranée sous couvert d'« exercices conjoints » avec des alliés régionaux. Les renseignements suggèrent que ce prétendu entraînement est un prétexte pour démontrer la puissance navale américaine à proximité de nos eaux, une action que nous ne pouvons ignorer. En tant que commandant des forces de défense côtière syriennes, votre mission est de surveiller et de défendre nos eaux territoriales contre toute intrusion. La tension est vive et des navires de guerre américains sont stationnés juste à l'extérieur de nos frontières, ce qui représente un risque sérieux pour la souveraineté syrienne. Les sites de missiles côtiers, les patrouilleurs et les unités de défense aérienne sont en état d'alerte maximale, prêts à réagir rapidement si la flotte américaine pénètre dans les eaux syriennes ou entreprend des actions provocatrices. Soyez prudents afin d'éviter une escalade inutile, mais restez prêts à défendre notre territoire si les Américains tentent leur chance. Le succès de cette mission dépend de votre capacité à démontrer la détermination de la Syrie tout en trouvant le délicat équilibre entre vigilance et retenue. Le monde entier vous observe, et c'est à vous de faire savoir que la Syrie ne reculera pas.
[Language_ru]
Name=Не грози Техасу (за Красных)
Description=США под предлогом «совместных учений» с союзниками в регионе ввели в Средиземное море корабли «Техас» и «Вирджиния». Разведка предпологает, что эти так называемые учения – предлог для демонстрации морской мощи США вблизи наших вод. Мы не можем игнорировать данные действия. Как командующий береговой обороной Сирии вы обязаны внимательно наблюдать за их действиями и пресечь любое нарушения наших территориальных вод. Уровень напряженности в регионе очень высок, американские корабли находятся вблизи наших границ, неся угрозу суверенитету Сирии. Береговые ракетные батареи, катера и силы ПВО приведены в состояние полной боевой готовности, чтобы отразить любое нарушение наших границ и пресечь возможные провокационные действия США. Действуйте с осторожностью, избегайте ненужной эскалации, но будьте готовы защищать нашу территорию, если американцы вздумают испытать свою удачу. Успех этой операции зависит от вашей способности продемонстрировать нашу решимость, балансируя при этом между бдительностью и осторожностью. Весь мир смотрит на нас и от вас зависит, сумеет ли Сирия показать, что она готова защищаться.
[Language_de]
Name=Don't Mess With Texas (Rote Seite)
Description=Die USA haben die USS Texas und die USS Virginia unter dem Vorwand gemeinsamer Manöver mit regionalen Verbündeten ins Mittelmeer entsandt. Geheimdienstberichte legen nahe, dass dieses sogenannte Manöver ein Vorwand ist, um die Stärke der US-Marine in direkter Nähe unserer Gewässer zu demonstrieren – ein Vorgehen, das wir nicht ignorieren können. Als Kommandeur der syrischen Küstenverteidigung liegt es an Ihnen, jede Verletzung unserer Hoheitsgewässer zu registrieren und abzuwehren. Die Spannungen sind groß und amerikanische Kriegsschiffe patrouillieren direkt vor unseren Gewässern, was eine ernsthafte Bedrohung für die Souveränität Syriens darstellt. Raketenstellungen, Patrouillenboote und Luftverteidigungseinheiten sind in höchster Alarmbereitschaft und bereit, sofort zu reagieren, falls die US-Flotte unsere Gewässer verletzt. Lassen Sie Vorsicht walten, um unnötige Eskalationen zu vermeiden, doch seien Sie vorbereitet, unser Territorium um jeden Preis zu verteidigen, falls die Amerikaner zu weit gehen. Der Erfolg dieser Mission hängt davon ab, Syriens Entschlossenheit zu demonstrieren und dabei das Gleichgewicht zwischen Wachsamkeit und Zurückhaltung zu wahren. Die Welt beobachtet jeden Schritt und es liegt an Ihnen, die klare Botschaft zu senden, dass Syrien nicht zurückweichen wird.
[Language_cn]
Name=别惹德克萨斯（红方）
Description=美国以和当地盟友举行“联合演习”的借口将德克萨斯号和弗吉尼亚号部署到了地中海。情报显示美国海军所谓演习的真实目的是在我方水域附近耀武扬威，我们不能坐视不管。作为叙利亚海防部队的指挥官，你的任务是监视和阻止任何入侵我方领海的行为。局势已高度紧张，美国军舰就在我们的边境外，对叙利亚主权构成了严重威胁。沿海导弹阵地、巡逻艇和防空部队已进入高度戒备状态，准备在美国舰队进入叙利亚水域或采取任何挑衅行为时迅速作出反应。谨慎行事，避免不必要的升级，但如果美国人想玩火，我们必须保卫自己的领土。此次任务的成败取决于你在警惕和克制之间保持平衡，同时展现叙利亚决心的能力。全世界都在关注，你必须传递一条信息——叙利亚不会退缩。
[Language_ko]
Name=텍사스에게 개기지 말것(레드포)
Description=미군은 지역 동맹국과의 "공동 훈련"이라는 명목으로 USS 텍사스와 USS 버지니아를 지중해에 배치했습니다. 정보에 따라 이 훈련이라는 것은 우리 해역 근처에서 미 해군의 힘을 과시하기 위한 구실이며, 우리는 이를 무시할 수 없습니다. 시리아 해안 방위군 사령관으로서 귀하의 임무는 우리 영해에 대한 모든 침입을 감시하고 방어하는 것입니다. 긴장이 고조되고 있으며, 미국 군함은 우리 국경 바로 바깥에 주둔하고 있어 시리아 주권에 심각한 위험을 초래하고 있습니다. 해안 미사일 기지, 순찰선, 방공 부대는 고도의 경계태세를 갖추고 있으며, 미국 함대가 시리아 해역을 침범하거나 도발적인 행동을 취할 경우 신속히 대응할 준비가 되어 있습니다. 불필요한 긴장 고조를 피하기 위해 주의를 기울이되, 미국이 그들의 운을 시험할 경우 우리 영토를 방어할 준비를 하십시오. 이 임무의 성공은 경계와 자제 사이의 섬세한 균형을 유지하며, 시리아의 결의를 보여줄 수 있는 귀하의 능력에 달려 있습니다. 전 세계가 지켜보고 있으며, 시리아가 물러서지 않을 것이라는 메시지를 보내는 것은 당신에게 달려 있습니다.
[Environment]
Date=1976,10,26
Time=4,0
ConvertTimeToLocal=False
SeaState=5
Clouds=Broken
WindDirection=N
MapCenterLatitude=54.27
MapCenterLongitude=-26.28
LoadBackgroundData=False
[Mission]
Difficulty=3
PlayerTaskforce=Taskforce2
EnemyTaskforce=Taskforce1
Taskforce1_Nation=Blue
Taskforce2_Nation=Red
NumberOfTaskforce1Vessels=4
NumberOfTaskforce2Vessels=4
NumberOfNeutralVessels=1
NumberOfTaskforce1Submarines=0
NumberOfTaskforce2Submarines=0
NumberOfNeutralSubmarines=0
NumberOfTaskforce1Aircraft=0
NumberOfTaskforce2Aircraft=3
NumberOfNeutralAircraft=0
NumberOfTaskforce1Helicopters=0
NumberOfTaskforce2Helicopters=0
NumberOfNeutralHelicopters=0
NumberOfTaskforce1LandUnits=0
NumberOfTaskforce2LandUnits=2
NumberOfNeutralLandUnits=0

Taskforce1_NumberOfFormations=1
Taskforce1_Formation1=Taskforce1Vessel1,Taskforce1Vessel2,Taskforce1Vessel3,Taskforce1Vessel4|Texas Flotilla|Echelon|1.5|OverrideSpawnPositions
Taskforce2_NumberOfFormations=2
Taskforce2_Formation1=Taskforce2Vessel1,Taskforce2Vessel2,Taskforce2Vessel3,Taskforce2Vessel4|Syrian Patrol Boats|Echelon|1.5|OverrideSpawnPositions
Taskforce2_Formation2=Taskforce2Aircraft1,Taskforce2Aircraft2|Syrian Air Patrol|Vic|0.1|OverrideSpawnPositions

[ ============================== Land Units ============================== ]
[ ---------- Taskforce1 ---------- ]
[ ---------- Taskforce2 ---------- ]
[Taskforce2LandUnit1]
Type=wp_cross_slot
VariantReference=Variant3
RadarsActive=True
CrewSkill=Seasoned
RelativePositionInNM=3756.77,low,-1128.46
Nation=Syria
Heading=0

[Taskforce2LandUnit2]
Type=wp_airbase_2
VariantReference=Variant5
CrewSkill=Trained
GeoPosition=35.9708,36.7797,low
#RelativePositionInNM=3756.77,low,-1130.51
Heading=104
CustomAirGroup=True
wp_mig-23ms=Squadron7,10
wp_mig-21=Squadron38,12|Squadron45,12

[ ----------   Neutral  ---------- ]
[ ================================ Vessels =============================== ]
[ ---------- Taskforce1 ---------- ]
[Taskforce1Vessel1]
Type=usn_cgn_virginia
VariantReference=Variant2
RadarsActive=True
CrewSkill=Veterans
RelativePositionInNM=3670.5,0,-1148.44
Telegraph=3
Heading=31
Waypoints=3677.669,0,-1136.425|3694.794,0,-1108.342|3666.579,0,-1095.268|3646.199,0,-1092.178|3630.514,0,-1094.104|3608.503,0,-1099.057|3424.689,0,-1147.3|3168.865,0,-1207.684

[Taskforce1Vessel2]
Type=usn_cgn_virginia
VariantReference=Variant1
MissionType=Patrol
RadarsActive=True
CrewSkill=Seasoned
RelativePositionInNM=3670.91,0,-1149.22
Telegraph=3
Heading=31

[Taskforce1Vessel3]
Type=usn_ddg_adams_late
VariantReference=Variant6
RadarsActive=True
CrewSkill=Seasoned
RelativePositionInNM=3669.53,0,-1147.96
Telegraph=3
Heading=31

[Taskforce1Vessel4]
Type=usn_ddg_adams_late
VariantReference=Variant8
RadarsActive=True
CrewSkill=Seasoned
RelativePositionInNM=3670.5,0,-1150.09
Telegraph=3
Heading=31

[ ---------- Taskforce2 ---------- ]
[Taskforce2Vessel1]
SetSelected=True
Type=wp_skr_petya3
VariantReference=Variant2
RadarsActive=True
CrewSkill=Trained
RelativePositionInNM=3698.43,0,-1142.64
Telegraph=5
Heading=265
Waypoints=3689.375,0,-1143.472|3672.538,0,-1147.823|3690.689,0,-1152.124|3729.284,0,-1142.595

[Taskforce2Vessel2]
Type=wp_skr_petya3
VariantReference=Variant1
RadarsActive=True
CrewSkill=Trained
RelativePositionInNM=3698.38,0,-1142.55
Telegraph=4
Heading=265

[Taskforce2Vessel3]
Type=wp_ptg_osa1
VariantReference=Variant143
CrewSkill=Trained
RelativePositionInNM=3698.74,0,-1142.47
Telegraph=4
Heading=265

[Taskforce2Vessel4]
Type=wp_ptg_osa1
VariantReference=Variant144
CrewSkill=Trained
RelativePositionInNM=3698.54,0,-1142.58
Telegraph=4
Heading=265

[ ----------   Neutral  ---------- ]
[NeutralVessel1]
Type=civ_ms_amra
VariantReference=Variant10
MissionType=NoMission
WeaponStatus=Tight
RadarsActive=True
ActiveSonarsEnabled=False
TowedArrayDeployed=False
TowedDecoyDeployed=False
CrewSkill=Trained
Stores=Full
Damage=None
RelativePositionInNM=3663.3,0,-1132.74
Telegraph=3
Nation=UK
Heading=206
Waypoints=3658.448,0,-1142.91|3653.604,0,-1151.429|3661.472,0,-1195.796|3668.754,0,-1279.836

[ =============================== Aircraft =============================== ]
[ ---------- Taskforce1 ---------- ]
[ ---------- Taskforce2 ---------- ]
[Taskforce2Aircraft1]
Type=wp_mig-23ms
SquadronReference=Squadron7
LoadoutVariant=CAS
WeaponStatus=Free
RadarsActive=True
CrewSkill=Trained
RelativePositionInNM=3751.4,20000,-1131.97
Telegraph=3
Heading=243
HomeBase=Taskforce2LandUnit2
Waypoints=3748.671,20000,-1133.338|3731.499,20000,-1136.38|3709.365,20000,-1139.855|3673.51,20000,-1147.86|3728.763,20000,-1178.328|3827.604,20000,-1180.901

[Taskforce2Aircraft2]
Type=wp_mig-23ms
SquadronReference=Squadron7
LoadoutVariant=CAS
WeaponStatus=Free
RadarsActive=True
CrewSkill=Trained
RelativePositionInNM=3751.4,20000,-1131.97
Telegraph=3
Heading=243
HomeBase=Taskforce2LandUnit2

[Taskforce2Aircraft3]
Type=wp_il-38
SquadronReference=Default
LoadoutVariant=ASW
RadarsActive=True
CrewSkill=Trained
RelativePositionInNM=3756.08,3000,-1129.47
Telegraph=3
Heading=-90
Nation=Syria
HomeBase=Taskforce2LandUnit2

