[General]
Hidden=True
#Type=Tutorial
Type=Scenario

[Language_en]
Name=Demo Scenarios
Description=Scenarious of this folder are designed to demonstrate some features or to have development documentation

[Language_cn]
Name=示範場景
Description=此資料夾中的場景用於展示部分功能，或作為開發文件參考
