[Debug]
#記錄模式定義。
#預設 = None
#用於個人化記錄
LogMode=Ivan

#允許在此特定任務中停用地形。
#預設 = False
#覆寫 usersettings.ini 中的設定
//DisableTerrain=False

#即使設定檔停用音樂，也可在此任務中強制載入音樂。
#預設 = False
#覆寫 config.ini 中的設定
//ForceMusicLoadig=False

#允許覆寫非玩家單位的控制選項。
#預設 = False
//AllowControlOfEnemyUnits=False


#允許覆寫未識別非玩家單位的可視設定。
#預設 = False
//ShowUnidentifiedUnitsIn3D=False

#允許啟用 WeaponTestMode。
#預設 = False
//WeaponTestMode=False

#允許禁止敵方 AI 在此特定任務中攻擊玩家。
#預設 = True
AllowEnemyUnitsAttackPlayer=False

#允許覆寫所有敵方（由 'EnemyTaskforce' 定義）單位的武器狀態
#預設 = 不寫此行
//EnemyWeaponStatus=Tight

#DevMode GUI 的初始縮放比例。
#可用值 = Auto,<數字>
#預設 = Auto
#DevModeGUIScale=Auto
DevModeGUIScale=1
#縮放調整按鈕會加上或減去的數值

[ ============================== Languages ============================== ]

#任務本地化在此完成。每個 [Language_???] 區段都應包含翻譯成對應語言的相同文字
[Language_en]
#Scenario menu 中顯示的任務名稱
Name=Info Mission
Description=This mission contains \ndocumentation and <Span Foreground="{StaticResource Brush.Glyph.Highlighted}">examples</Span> of what is possible in the ini files

#Intel items - messages which will be displayed in the "intel" tab of message log at given time during mission
#Time format: <hour>,<minutes> or <year>,<month>,<day>,<hour>,<minutes>
#Note: Message is displayed if current time/date is bigger than given one, so message with time 1789,7,14,14,20 for example, woould be displayed right at the start of this mission
#IMPORTANT: Works for EVERY taskforce so cant really be used in scenarios with switchable sides.
NumberOfIntelItems=4
IntelligenceTime1=5, 30
IntelligenceItem1=Test 1
IntelligenceTime2=1974, 5, 9, 5, 45
IntelligenceItem2=Test 2
IntelligenceTime3=6, 00
IntelligenceItem3=Test 3
IntelligenceTime4=7, 00
IntelligenceItem4=Test 4

#Messages for triggers
#Template: <message name>=<message>
#message name is specified in trigger
#message composition: <Caption>|<Message text>|<Exit Button Variant>,<Exit Button Variant>,<Exit Button Variant>...
Taskforce1StartMessage=<size=40>Message Caption</size>|Message example:\n\n<size=15> size=15 </size>\n<color={*}ffc68c>color={*}ffc68c</color>|Variant 1, Variant 2

[Language_cn]
#Scenario menu 中顯示的任務名稱
Name=任務檔案資訊
Description=這個任務包含 ini 檔可實現內容的\n文件與 <Span Foreground="{StaticResource Brush.Glyph.Highlighted}">範例</Span>

#情報項目：會在任務中的指定時間顯示於訊息記錄的「情報」分頁。
#時間格式：<時>,<分> 或 <年>,<月>,<日>,<時>,<分>
#注意：當目前時間/日期晚於指定值時就會顯示訊息；例如時間設為 1789,7,14,14,20 的訊息，會在本任務開始時立即顯示。
#重要：這會套用到每一支 taskforce，因此不太適合用在可切換陣營的場景中。
NumberOfIntelItems=4
IntelligenceTime1=5, 30
IntelligenceItem1=測試 1
IntelligenceTime2=1974, 5, 9, 5, 45
IntelligenceItem2=測試 2
IntelligenceTime3=6, 00
IntelligenceItem3=測試 3
IntelligenceTime4=7, 00
IntelligenceItem4=測試 4

#觸發器使用的訊息
#範本：<訊息名稱>=<訊息內容>
#訊息名稱會在觸發器中指定
#訊息組成：<標題>|<訊息內文>|<結束按鈕選項>,<結束按鈕選項>,<結束按鈕選項>...
Taskforce1StartMessage=<size=40>訊息標題</size>|訊息範例：\n\n<size=15> size=15 </size>\n<color={*}ffc68c>color={*}ffc68c</color>|選項 1, 選項 2


[Environment]
#任務開始日期。
#<年>,<月>,<日>
Date=1974,5,9

#任務開始時間。
#<時>,<分>
Time=5,30

#海況
#可用值：0-12
#建議值：1-10
#預設 = 4
SeaState=3

#風向
#可用值：N, NE, E, SE, S, SW, W, NW
#預設 = N
WindDirection=SW

#雲量。可用值為 clouds.ini 中的區段名稱（當然不包含 [General]）
#目前可用值：Clear,Scattered,Scattered_1,Scattered_2,Broken,Broken_2,Broken_3,Overcast
Clouds=Broken_2

#特殊天氣。可列出多個值
#可用值：Rain,Snow,Fog,Thunderstorm
#預設 = <無>
#注意：Thunderstorm 只有在 Overcast 雲層下可見
#注意：Fog 目前會嚴重影響雲層顯示
//Weather=Rain,Thunderstorm

#地圖位置。任務區域中心位置請使用真實世界座標

#亞得里亞海，蒙特內哥羅，蘇托莫雷
MapCenterLatitude=42.1
MapCenterLongitude=19

#愛琴海
#MapCenterLatitude=36
#MapCenterLongitude=25

#阿爾漢格爾斯克
#MapCenterLatitude=64.55
#MapCenterLongitude=40.5

#挪威卑爾根
#MapCenterLatitude=60.407
#MapCenterLongitude=5.289166

#埃姆登
#MapCenterLatitude=53.307391
#MapCenterLongitude=7.145060

#GIUK
#MapCenterLatitude=58
#MapCenterLongitude=-23

#蘇聯格雷米哈
#MapCenterLatitude=68.05972222
#MapCenterLongitude=39.51361111

#夏威夷
#MapCenterLatitude=20.466
#MapCenterLongitude=-156.4328

#檀香山
#MapCenterLatitude=21.3400792
#MapCenterLongitude=-157.9728127

#冰島南部
#MapCenterLatitude=63.796061
#MapCenterLongitude=-22.552217

#伊朗，中部
#MapCenterLatitude=30.386823458
#MapCenterLongitude=53.62415257

#裡海
#MapCenterLatitude=43.4
#MapCenterLongitude=50

#哈爾克島
#MapCenterLatitude=29.2697578
#MapCenterLongitude=50.2510527

#列寧格勒
#MapCenterLatitude=59.93
#MapCenterLongitude=30.2

#摩爾曼斯克
#MapCenterLatitude=68.999203
#MapCenterLongitude=33.036945

#納爾維克峽灣
#MapCenterLatitude=68.426695
#MapCenterLongitude=17.137733

#美國紐約
#MapCenterLatitude=40.548803
#MapCenterLongitude=-74.038944

#新潟
#MapCenterLatitude=37.9497108
#MapCenterLongitude=139.0016708

#美國諾福克
#MapCenterLatitude=36.93111111
#MapCenterLongitude=-76.33055556

#莫士比港
#MapCenterLatitude=-9.570733
#MapCenterLongitude=147.116973

#雷扎爾菲厄澤
#MapCenterLatitude=65.021641
#MapCenterLongitude=-13.988764

#西班牙羅塔
#MapCenterLatitude=36.622941
#MapCenterLongitude=-6.342686

#塞倫蓋提
#MapCenterLatitude=-2.1189069
#MapCenterLongitude=34.1733967

#索羅門群島
#MapCenterLatitude=-9.144619
#MapCenterLongitude=160.189064

#荷姆茲海峽
#MapCenterLatitude=26.584155
#MapCenterLongitude=56.245727

#荷姆茲海峽，阿巴斯港
#MapCenterLatitude=27.199160915
#MapCenterLongitude=56.2132273

#東京灣
#MapCenterLatitude=35.279829
#MapCenterLongitude=139.392115


#覆寫 \ui\<SelectedUIFolder>\Settings_UI_Tactical.ini 中指定的初始小地圖縮放等級
#預設 = <UI 設定。預設 = 8>
//MapInitialZoom=10

[Mission]
#這用於定義博物館「任務」。你永遠不會想使用它。
#預設 = False
//MuseumMission=False

#Scenario menu 中顯示的星等數量
Difficulty=1

#Taskforce 名稱定義。可用於輕鬆切換可遊玩陣營
#Taskforce 名稱會定義區段名稱，因此若 PlayerTaskforce=SomeName，就應使用 NumberOfSomeNameVessels 之類的鍵
#為了方便使用，建議直接使用 Taskforce1 與 Taskforce2 名稱。
PlayerTaskforce=Taskforce1
EnemyTaskforce=Taskforce2

#Taskforce 國籍。目前只決定任務期間播放的音樂。
Taskforce1_Nation=Soviet
Taskforce2_Nation=USA

#對應 taskforce 單位類型的數量。用於讀取單位區段
#預設 = 0
NumberOfTaskforce1LandUnits=3
NumberOfTaskforce2LandUnits=0
NumberOfNeutralLandUnits=0

NumberOfTaskforce1Vessels=5
NumberOfTaskforce2Vessels=1
NumberOfNeutralVessels=4

NumberOfTaskforce1Submarines=3
NumberOfTaskforce2Submarines=
NumberOfNeutralSubmarines=

NumberOfTaskforce1Aircraft=1
NumberOfTaskforce2Aircraft=
NumberOfNeutralAircraft=

NumberOfTaskforce1Helicopters=
NumberOfTaskforce2Helicopters=
NumberOfNeutralHelicopters=

#隊形。
#隊形區段數量
#預設 = 0
Taskforce1_NumberOfFormations=2
#隊形資料
#範本：<隊形領隊>, <隊形成員>, <隊形成員>..., <隊形成員>|<隊形名稱>|<隊形樣式>|<間距>|<特殊設定>
#<隊形名稱> 可以是任何字串，也可以完全不指定。預設 = <空字串>
#<隊形樣式> 也可以不指定。預設 = Loose
#可用值：
#None, Loose, Circle, Vic, Echelon, LineAbreast, LineAstern, Box, Convoy, Battlegroup 
#Loose, Circle, Vic, Echelon, LineAbreast, LineAstern, Box - 具形狀的隊形
#Convoy - 開發中的隊形，目前約 50% 可用
#Battlegroup - 供 InstantAction 使用，在其他地方效果不是很好
#<間距>：適用時以英里為單位
#<特殊設定> 可用值：OverrideSpawnPositions 只有在其他部分皆有定義時才有效。會將單位傳送到其隊形位置
Taskforce1_Formation1=Taskforce1Vessel2,Taskforce1Vessel3|第1隊形|Vic|0.1//|OverrideSpawnPositions

Taskforce1_Formation2=Taskforce1Vessel4,Taskforce1Vessel5|第2隊形|Vic|0.1|OverrideSpawnPositions


#觸發器數量。用於讀取觸發器區段
NumberOfTriggers=5


[ ============================== Land Units ============================== ]
[ ---------- Taskforce1 ---------- ]
[Taskforce1LandUnit1]
Type=wp_silkworm_launcher
VariantReference=Variant1
#Low - 會貼齊地面。在斜坡地形或大型物件上效果不好
RelativePositionInNM=6.3,low,0.3
Heading=250

[Taskforce1LandUnit2]
Type=wp_sam_site_sa-5
VariantReference=Variant1
RelativePositionInNM=25.41,234,9.14
Heading=15

[Taskforce1LandUnit3]
Type=wp_large_pvo_airbase
VariantReference=Variant1
#允許使用精確 Unity 數值覆寫生成高度
RelativePositionInNM=14.8,154,14.99
OverrideSpawnHeightUnity=0.7
Heading=15

[ ---------- Taskforce2 ---------- ]
[ ----------   Neutral  ---------- ]
[ ================================ Vessels =============================== ]
[ ---------- Taskforce1 ---------- ]
[Taskforce1Vessel1] #大部分關於單位生成的資訊
#---------- 一般 ----------

#使單位不可控制，例如著陸狀態時。
#預設 = True
//Controllable=False
#使單位對其他 taskforce 的感測器隱形。
#預設 = False
//Undetectable=False

#控制此單位生成的機率
#可用值：0-1。小於 0 視為 0，大於 1 視為 1
#預設 = 1（一定生成）
//SpawnChance=0.5

#通常任務開始時會選取第一個玩家單位。此設定可覆寫該行為。
#注意：最後一個設為 'SetSelected=True' 的玩家單位會在任務開始時被選取。
#預設 = False
SetSelected=True

#單位 ini 檔名稱
#若有像 'Type=wp_takr_kiev,wp_em_sovremenny,wp_rkr_slava' 這樣的值清單，會從清單中隨機生成一個單位
Type=wp_takr_kiev

#這會定義艦名、塗裝與航空隊
#注意：Aircraft 與 Helicopters 會改用 'SquadronReference'
#可用值：Default, Random, Variant<number>
#預設 = Default
VariantReference=Variant2

#允許覆寫單位國籍
#對艦艇而言，這會自動覆寫桅旗貼圖
#Aircraft 與 Helicopters 也適用
#可用值：<NationName>
#預設 = variants 檔案中標示的單位國籍
//Nation=Pakistan

#允許覆寫單位桅旗貼圖
#Aircraft 與 Helicopters 通常不會使用
#可用值：<PathToTheFlag>
#預設 = variants 檔案中標示的旗幟
//FlagTexture=ships/materials/textures/flag_cyprus

#若單位有裝載配置，這會定義其 loadout。Aircraft、貨船與部分特殊案例會使用
#預設 = Default
//LoadoutVariant=Default

#---------- 航空隊 ----------
#完整替換艦上航空器。
#適用於空軍基地、航空母艦與搭載直升機的護航艦
#注意：不相容的航空器會被忽略。不可能超過容量載入
CustomAirGroup=True
wp_yak-38=Squadron2,12|Squadron4,12
wp_mig-23a=Squadron1,6 //<-- 基輔級不支援 MiG-23A，因此不會加入
wp_ka-25=Squadron1,4
wp_ka-27=Squadron1,16  //<-- 由於基輔級容量（36 架）限制，只會加入 8 架

#---------- 感測器 ----------
#允許開啟/關閉特定單位的感測器（若適用）。
VisualSystemsOn=True        // 預設 = True。警告：除了使用 DevMode/Sensors 外，無法重新開啟
RadarsActive=True           // 預設 = False。警告：若啟用，水面與空中搜索雷達都會啟用。
TowedArrayDeployed=True     // 預設 = False。
ActiveSonarsEnabled=True    // 預設 = False。若拖曳聲納是主動 VDS，也必須啟用此項才會部署
TowedDecoyDeployed=False    // 預設 = False。這裡不作用，因為基輔級沒有拖曳誘餌

#---------- 武器 ----------
#設定單位的武器狀態
#可用值：Hold, Tight, Free
#預設 = Tight
#注意：敵方 taskforce 單位可由 [Debug]/EnemyWeaponStatus 設定覆寫
//WeaponStatus=Tight

#---------- 其他 ----------

#單位乘員熟練度。目前只影響 TMA 速度。未來還有很大發展空間……
#可用值：Green, Trained, Seasoned, Veterans, Ultra
#預設 = Green
CrewSkill=Veterans

# ---------- 生成位置 ----------

#預設 = 0,0,0
#0) 地理位置。
#直接位置定義
#<緯度, 經度, 高度>
#高度單位為英尺，但也可使用文字。請參考潛艦與航空器範例（在 NM 中也使用相同文字。注意：在 GP 中高度是第 3 個參數）
GeoPosition=38.0753,21.9964,3392

#定義生成位置的多種方式：
#x 為負值代表向西，z 為負值代表向北，高度（y）單位為英尺

#預設 = 0,0,0
#1) 直接位置。
#指定相對任務區域中心的英里偏移
#<海里,英尺,海里>
#高度單位為英尺，但也可使用文字。請參考潛艦與航空器範例
RelativePositionInNM=-0,0,-20
#可以使用其他單位位置，而非地圖中心。
#重要：該單位必須已經定義。因此可以在玩家單位周圍生成敵方單位，但不能反過來
//PositionRelativeTo=Taskforce1LandUnit1  

#2) 在某位置周圍隨機生成
#
#範圍單位為英里
//RandomSpawnCenter=0,0,0
#也可使用：RandomSpawnCenter=Taskforce1LandUnit1，規則同上
//RandomSpawnRange=5,10        //會在距離中心 5 到 10 海里的隨機範圍生成
//RandomSpawnDirection=-45,45  //會以 -45 到 45 度的隨機絕對方位生成（西北到東北）
//PositionRelativeTo=Taskforce1LandUnit1  // 也可在此用於航向定義

#航向
#預設 = 0
Heading=-140
//Heading=0,-140,0     // 完整旋轉向量
//Heading=Parent       // 將航向設為等同 "PositionRelativeTo" 單位的航向
#可圍繞選定航向隨機化航向
RandomizeCourse=-45,45  //結果航向會是 Heading 加上 -45 到 45 度的隨機值。（僅水平）

#車鐘/速度設定
#可用值：艦艇 -1 - 5，航空器 2 - 5
#預設 = 0
Telegraph=2

#---------- 航點 ----------
Waypoints=Turn,0,20,current   //<- 會在單位前方 20 海里產生航點
#Course,-100/-90,10,current,32|RandomTurns,20,-30/30,2/4,current,10/20|-13,0,4
#Turn,-30/35,2,current|Turn,-30/35,2,current|Turn,-30/35,2,current|Turn,-30/35,2,current|Turn,-30/35,2,current|Turn,-30/35,2,current|Turn,-30/35,2,current|Turn,-30/35,2,current

#航點規則資訊：
#<X>,<Z> = <英里Min/英里Max>					相對中心的世界座標／相對 parent 的相對座標，單位為英里
#<height> = <英尺Min/英尺Max>, p/psd/periscope, current, parent		高度的各種定義
#<time> = <秒Min/秒Max>									航點刪除前的時間。可選
#<angle> = <度Min/度Max>
#<number> = <整數>								建立的隨機航點數量
#<range> = <英里Min/英里Max>					到航點的距離
#<parent> = 單位區段名稱。必須位於目前單位之前

#<X>,<height>,<Z>,<time>										依座標建立的一般世界航點
#Course,<courseMin/courseMax>,<range>,<height>,<time>		依世界方位與距離建立的一般世界航點
#Turn,<angle>,<range>,<height>,<time>						依目前航向轉向 <angle> 度建立的一般世界航點
#RandomTurns,<number>,<angle>,<range>,<height>,<time>		自動產生 <number> 個隨機 "Turn" 類型航點

#ToSpawnPosition,<parent>,<height>,<time>					位於 <parent> 生成位置的一般世界航點
#ToCurrentPosition,<parent>,<height>,<time>					位於執行航點當下 <parent> 位置的一般世界航點

#RelativeFixed,<parent>,<X>,<height>,<Z>,<time>			可抵達、會隨 parent 旋轉的相對航點
#RelativeLoose,<parent>,<X>,<height>,<Z>,<time>			可抵達、不會隨 parent 旋轉的相對航點
#FollowFixed,<parent>,<X>,<height>,<Z>,<time>			不可抵達、會隨 parent 旋轉的相對航點
#FollowLoose,<parent>,<X>,<height>,<Z>,<time>			不可抵達、不會隨 parent 旋轉的相對航點

#無條件攻擊
#很粗略，或許應改由觸發器取代
//Attack=Taskforce2Vessel1,1,wp_ss-n-12,4,wp_1|Taskforce2Vessel1,10
#可用變體：範本：
#targetObject,timeOfAttack,ammunitionFileName,numberOfShots,waypointNumber|<下一筆>
# targetObject：必要，一律預期為第 1 項
# timeOfAttack：可選，一律預期為第 2 項。以任務開始或抵達航點（若指定）後的秒數計算。
# ammunitionFileName（可選），可位於第 3 項之後任意位置
# numberOfShots（可選），可位於第 3 項之後任意位置
# waypointNumber（可選），可位於第 3 項之後任意位置。允許在抵達指定航點後才開始攻擊；若航點不存在，攻擊會取消

[Taskforce1Vessel2]
SpawnChance=1
Type=wp_rkr_slava
VariantReference=Random

#斯拉瓦會固定生成在基輔以西 5-10 英里處
RandomSpawnCenter=Taskforce1Vessel1
RandomSpawnRange=5,10        //會在距離中心 5 到 10 海里的隨機範圍生成
RandomSpawnDirection=-90     //會在 SpawnCenter 以西生成

PositionRelativeTo=Taskforce1Vessel1  // 也可在此用於航向定義
Heading=Parent

Telegraph=2
Waypoints=RandomTurns,20,-30/30,2/4,current,10/20|-13,0,4

[Taskforce1Vessel3]
Type=wp_rkr_kynda
VariantReference=Random
RelativePositionInNM=-2,0,0
Heading=-140
Telegraph=2
Waypoints=-2,0,-3|240,0,83

[Taskforce1Vessel4]
SpawnChance=1
Type=usn_dd_spruance
VariantReference=Random

#斯拉瓦會固定生成在基輔以西 5-10 英里處
RandomSpawnCenter=Taskforce1Vessel1
RandomSpawnRange=5,10        //會在距離中心 5 到 10 海里的隨機範圍生成
RandomSpawnDirection=80,100  //會在 SpawnCenter 以東生成

PositionRelativeTo=Taskforce1Vessel1  // 也可在此用於航向定義
Heading=Parent

Telegraph=2
Waypoints=Turn,-30/35,2,current|Turn,-30/35,2,current|Turn,-30/35,2,current|Turn,-30/35,2,current|Turn,-30/35,2,current|Turn,-30/35,2,current|Turn,-30/35,2,current|Turn,-30/35,2,current

[Taskforce1Vessel5]
Type=usn_ddg_adams_late
VariantReference=Random
RelativePositionInNM=-12,0,0
Heading=-140
Telegraph=2


[ ---------- Taskforce2 ---------- ]
[Taskforce2Vessel1]
Type=usn_cgn_virginia
VariantReference=Random
RadarsActive=True
RelativePositionInNm=-130,0,-20
Heading=60
Telegraph=3
Waypoints=Turn,0,50,0



[ ----------   Neutral  ---------- ]
[NeutralVessel1]
Type=civ_ms_freighter_a
VariantReference=Random

#商船可用變體：
#DryCargo,Containers,Vehicles,Munitions,Fertilizer,MilitaryVehicles,Lighters,Oil,Ore
#但實際仍取決於 vessel ini 檔中寫了什麼
LoadoutVariant=MilitaryVehicles

RandomSpawnCenter=-40,0,-30
RandomSpawnRange=5,25
RandomSpawnDirection=-180,180

Heading=0
RandomizeCourse=-180,180
Telegraph=3
Waypoints=RandomTurns,5,-30/30,10,current

[NeutralVessel2]
Type=civ_ms_encounter
VariantReference=Random
LoadoutVariant=Munitions

RandomSpawnCenter=-40,0,-30
RandomSpawnRange=5,25
RandomSpawnDirection=-180,180

Heading=0
RandomizeCourse=-180,180
Telegraph=3
Waypoints=RandomTurns,5,-30/30,10,current

[NeutralVessel3]
Type=civ_ms_mairangi_bay
VariantReference=Random
LoadoutVariant=Containers

RandomSpawnCenter=-40,0,-30
RandomSpawnRange=5,25
RandomSpawnDirection=-180,180

Heading=0
RandomizeCourse=-180,180
Telegraph=3
Waypoints=RandomTurns,5,-30/30,10,current

[NeutralVessel4]
Type=civ_ms_irkutsk
VariantReference=Random
LoadoutVariant=MilitaryVehicles

RandomSpawnCenter=-40,0,-30
RandomSpawnRange=5,25
RandomSpawnDirection=-180,180

Heading=0
RandomizeCourse=-180,180
Telegraph=3
Waypoints=RandomTurns,5,-30/30,10,current

[ ============================== Submarines ============================== ]
[ ---------- Taskforce1 ---------- ]
[Taskforce1Submarine1]
Type=wp_ssgn_echo2
VariantReference=Random

#<height> 的可用值
#<number> - 精確深度，單位為英尺
#periscope - 潛望鏡深度（也接受 p 與 psd）
#shallow,abovelayer,belowlayer,deep,verydeep - 與遊戲內深度設定相同
RelativePositionInNm=-10,0,-15
Heading=-90
Telegraph=2
Waypoints=Turn,0,10,0

[Taskforce1Submarine2]
Type=wp_ssgn_charlie1
VariantReference=Variant1
RelativePositionInNm=-0,p,-1
Heading=0
Telegraph=0
Waypoints=Turn,0,10,current

[Taskforce1Submarine3]
Type=usn_ssn_sturgeon
VariantReference=Random
TowedArrayDeployed=True
RelativePositionInNm=-90,shallow,-18
Heading=-110
Telegraph=2
Waypoints=Turn,0,10,current

[ ---------- Taskforce2 ---------- ]
[Taskforce2Submarine2]
Type=usn_ssn_los_angeles
VariantReference=Default

RelativePositionInNm=0,-200,-5
Heading=0
Telegraph=4
Waypoints=0,-200,10

#將其他單位加入此潛艦可用飛彈攻擊的單位清單。
#僅與潛艦相關
#預設 = 無
AllowedTargetForMissiles=Taskforce1Vessel2

[ ----------   Neutral  ---------- ]
[ =============================== Aircraft =============================== ]
[ ---------- Taskforce1 ---------- ]
[Taskforce1Aircraft1]
Type=wp_tu-95rt
RadarsActive=True
#單位的母基地，例如機場
HomeBase=Taskforce1LandUnit3
RelativePositionInNm=-120,30000,-15
Heading=210
Waypoints=-126,30000,-25|-146,30000,-32|4,30000,400

[ ---------- Taskforce2 ---------- ]
[Taskforce2Aircraft1]
Type=wp_tu-95rt
RadarsActive=True
RelativePositionInNm=-190,30000,-90
Heading=0
Waypoints=-190,30000,100
[ ----------   Neutral  ---------- ]

[ ============================== Helicopters ============================= ]
[ ---------- Taskforce1 ---------- ]
[ ---------- Taskforce2 ---------- ]
[ ----------   Neutral  ---------- ]

[ ============================== Triggers ============================= ]
[Trigger1]  #任務結束
Name=任務結束
Description=自動結束任務的觸發器
Disabled=True
Condition_Type=Time
Condition_Time=10
Action_EndMission=True

[Trigger2]  #開始訊息 #移除 'disabled' 可查看
Disabled=True
Name=開始訊息
Description=任務開始時顯示的訊息
Condition_Type=Time
Condition_Time=0.5
Action_Taskforce1_Message=Taskforce1StartMessage
Action_Taskforce2_Message=Taskforce2StartMessage


[Trigger2] #一些動作資訊
Condition_Type=Time
Condition_Time=15

Action_Units=Taskforce1Aircraft2

Action_UnitRevealToTaskforce=Taskforce1  // 短暫向指定 taskforce 顯示單位
Action_SetEnabledStatus=False            // 停用或啟用單位
Action_DespawnUnits=True                 // 使單位消失。單位會消失，且不加入任務分數
Action_DestroyUnits=True                 // 摧毀單位。單位會爆炸/沉沒，且加入任務分數

[ ============================== BackgroundData ============================= ]
[BackgroundData]

#從 [BackgroundData] 區段列出的檔案載入地面單位
#預設 = False
//LoadBackgroundData=False


#以下請詢問 Matt
NumberOfBackgroundCityFiles=2
BackgroundCityFile1_Path=\campaigns\britishisles_cities.ini
BackgroundCityFile2_Path=\campaigns\cities.ini
NumberOfBackgroundAirportFiles=1
BackgroundAirportFile1_Path=\campaigns\airports.ini
BackgroundAirportFile1_DefaultGroupFile=\formations\New File.unitgroup
NumberOfBackgroundPortFiles=1
BackgroundPortFile1_Path=\campaigns\britishisles_ports.ini
BackgroundPortFile1_DefaultGroupFile=\formations\New File.unitgroup
NumberOfBackgroundInstallationFiles=1
BackgroundInstallationFile1_Path=\campaigns\britishisles_installations.ini
BackgroundInstallationFile1_DefaultGroupFile=\formations\New File.unitgroup
NumberOfBackgroundSceneryFiles=0
