[General]
Hidden=True
#Type=Tutorial
Type=Scenario

[Language_ja]
Name=デモシナリオ
Description=このフォルダ内のシナリオは、一部機能のデモンストレーション、または開発用リファレンスとしての提示を目的としている。

[Language_en]
Name=Demo Scenarios
Description=Scenarious of this folder are designed to demonstrate some features or to have development documentation


[Language_ko]
Name=데모 시나리오
Description=이 폴더 안에 있는 시나리오들은 일부 기능들을 보여주거나 혹은 추가적인 개발 단계를 기록하기 위해 제작되었습니다