[Debug]
DisableEnemyAIPlayer=True

[Language_ja]
Name=バルティム沖海戦 (1973年)
Description=第四次中東戦争（ヨム・キプル戦争）勃発から3日、イスラエル軍はアラブ諸国との激しい戦闘の最中にあった。ラタキア沖海戦で勝利を収めたばかりのサール型ミサイル艇部隊は、シナイ半島へ進撃するIDF（イスラエル国防軍）を支援すべく西への転進を命じられた。ポートサイドへと進出し、当該海域に展開するエジプト軍ミサイル艇部隊を捕捉・撃破せよ。
Taskforce1StartmessageMessage=<size=20>第四次中東戦争 - 第2部</size>\nバルティム沖海戦|第四次中東戦争（ヨム・キプル戦争）勃発から3日、イスラエル軍はアラブ諸国との激しい戦闘の最中にある。ラタキア沖海戦において勝利を収めたばかりのサール型ミサイル艇部隊は、シナイ半島へ進撃するIDFを支援すべく西への転進を命じられた。\n\n偵察により、アレクサンドリアから東進するエジプト軍のオーサ型ミサイル艇4隻が探知された。西へ進出し、これらを撃破せよ。なお、これほど沿岸に近い海域では多数の民間船の通航が予想される。\n\n少なくともイスラエル艦1隻が生存せねばならない。|作戦開始
Taskforce1Osasdestroyed-playervictoryMessage=勝利|勝利！エジプト軍ミサイル艇はすべて撃破された。見事な手際だ、指揮官。|作戦終了
Taskforce2Osasdestroyed-playervictoryMessage=<color=red>作戦失敗</color>|全戦力が喪失した。我々の敗北だ。
Taskforce1Playerdestroyed-playerdefeatMessage=敗北|敗北！全艦が作戦行動中に喪失した！|作戦終了
Objective_DestroyEnemyMissileBoats=敵ミサイル艇の撃破
Objective_OneShipMustSurvive=自軍艦艇が少なくとも1隻生存

[Language_en]
Name=The Battle of Baltim (1973)
Description=Three days into the Yom Kippur War, Israeli forces are heavily engaged in fighting against the Arab states. Your force of Sa'ar class missile boats, recently returning victorious from the Battle of Latakia, has been rerouted west to support the IDF advance into the Sinai. Proceed to Port Said, then locate and destroy the Egyptian missile boat flotilla in the area.
Taskforce1StartmessageMessage=<size=20>The Yom Kippur War - Part 2</size>\nTHE BATTLE OF BALTIM|Three days into the Yom Kippur War, Israeli forces are heavily engaged in fighting against the Arab states. Your force of Sa'ar class missile boats, recently returning victorious from the Battle of Latakia, has been rerouted west to support the IDF advance into the Sinai.\n\nReconnaissance has detected four Egyptian Osa class missile boats moving east from Alexandria. Proceed west and destroy them. Heavy civilian traffic is expected this close to the coast.\n\nAt least one Israeli ship must survive.|Start mission
Taskforce1Osasdestroyed-playervictoryMessage=VICTORY|Victory! The Egyptian missile boats have all been destroyed. Good work, Commander.|Exit mission
Taskforce2Osasdestroyed-playervictoryMessage=<color=red>Mission Failed</color>|All our forces are destroyed. You are defeated.
Taskforce1Playerdestroyed-playerdefeatMessage=DEFEAT|Defeat! All of your ships have been lost in action!|Exit mission
Objective_DestroyEnemyMissileBoats=Destroy enemy missile boats
Objective_OneShipMustSurvive=At least one player ship must survive

[Language_fr]
Name=La bataille de Baltim (1973)
Description=Trois jours après le début de la guerre du Kippour, les forces israéliennes sont engagées dans des combats intenses contre les États arabes. Votre flotte de vedettes lance-missiles de classe Saar, récemment revenue victorieuse de la bataille de Lattaquié, a été redirigée vers l'ouest pour soutenir l'avancée de Tsahal dans le Sinaï. Rendez-vous à Port-Saïd, puis localisez et détruisez la flottille de vedettes lance-missiles égyptiennes dans la zone.
Taskforce1StartmessageMessage=<size=20>La guerre du Kippour - 2ème partie</size>\nLA BATAILLE DE BALTIM|Trois jours après le début de la guerre du Kippour, les forces israéliennes sont engagées dans des combats intenses contre les États arabes. Votre force de vedettes lance-missiles de classe Sa'ar, récemment revenue victorieuse de la bataille de Lattaquié, a été redirigée vers l'ouest pour soutenir l'avancée de Tsahal dans le Sinaï.\n\nDes reconnaissances ont détecté quatre vedettes lance-missiles égyptiennes de classe Osa se déplaçant vers l'est depuis Alexandrie. Procédez vers l'ouest et détruisez-les. Un trafic civil important est attendu à cette distance de la côte.\n\nAu moins un navire israélien doit survivre.|Démarrer la mission
Taskforce1Osasdestroyed-playervictoryMessage=VICTOIRE|Victoire ! Les vedettes lance-missiles égyptiennes ont toutes été détruites. Bravo, Commandant.|Quitter la mission
Taskforce2Osasdestroyed-playervictoryMessage=<color=red>Mission échouée</color>|Toutes nos forces sont anéanties. Vous êtes vaincu.
Taskforce1Playerdestroyed-playerdefeatMessage=DEFAITE|Défaite ! Tous vos navires ont été perdus au combat !|Quitter la mission
Objective_DestroyEnemyMissileBoats=Détruire les vedettes lance-missiles ennemies
Objective_OneShipMustSurvive=Au moins l'un de nos navires doit survivre

[Language_ru]
Name=Бой у Балтима (1973)
Description=Бой у Балтима произошёл между ВМС Израиля и ВМС Египта во время «войны Судного дня». Бой разгорелся, когда шесть израильских ракетных катеров типа «Саар», направлявшихся в сторону Порт-Саида, были атакованы четырьмя египетскими ракетными катерами проекта 205, следовавшими из Александрии.
Taskforce1StartmessageMessage=<size=40>Бой у Балтима</size>|Добро пожаловать, командующий!\n\n<size=15>Ваша главная задача в этой миссии – обнаружить и потопить вражеские <color={*}ffc68c>ракетные катера</color>, направляющиеся к Вам.</size>|Боевая тревога!
Taskforce2StartmessageMessage=<size=40>Бой у Балтима</size>|Добро пожаловать, командующий!\n\n<size=15>Ваша главная задача в этой миссии – обнаружить и потопить вражеские <color={*}ffc68c>ракетные катера</color>, направляющиеся к Вам.</size>|Боевая тревога!
Taskforce1Osasdestroyed-playervictoryMessage=<color=lime>Миссия завершена!</color>|Хорошая работа, командующий! Противник разбит.
Taskforce2Osasdestroyed-playervictoryMessage=<color=red>Миссия провалена</color>|Все наши корабли уничтожены. Вы проиграли.
Taskforce1Playerdestroyed-playerdefeatMessage=<color=red>Миссия провалена</color>|Все наши корабли уничтожены. Вы проиграли.
Taskforce2Playerdestroyed-playerdefeatMessage=<color=lime>Миссия завершена!</color>|Хорошая работа, командующий! Противник разбит.
[Language_de]
Name=Die Schlacht von Baltim (1973)
Description=Drei Tage nach Beginn des Jom-Kippur-Krieges sind israelische Streitkräfte in Gefechte mit den arabischen Staaten verwickelt. Ihre Einheit aus Lenkwaffenschnellbooten der SA’AR-Klasse, die kürzlich siegreich aus der Schlacht von Latakia zurückgekehrt ist, wurde nach Westen umgeleitet, um den Vormarsch der IDF auf der Sinai-Halbinsel zu unterstützen. Verlegen Sie nach Port Said und suchen sowie vernichten Sie anschließend die ägyptische Lenkwaffenschnellboot-Flottille im Einsatzraum.
Taskforce1StartmessageMessage=<size=20>Der Jom-Kippur-Krieg – Teil 2</size>\nDIE SCHLACHT VON BALTIM|Drei Tage nach Beginn des Jom-Kippur-Krieges sind israelische Streitkräfte in Gefechte mit den arabischen Staaten verwickelt. Ihre Einheit aus Lenkwaffenschnellbooten der SA’AR-Klasse, die kürzlich siegreich aus der Schlacht von Latakia zurückgekehrt ist, wurde nach Westen umgeleitet, um den Vormarsch der IDF auf der Sinai-Halbinsel zu unterstützen.\n\nDie Aufklärung hat vier ägyptische Lenkwaffenschnellboote der OSA-Klasse erfasst, die von Alexandria ostwärts verlegen. Verlegen Sie nach Westen und vernichten Sie diese Einheiten. In Küstennähe ist mit starkem zivilen Schiffsverkehr zu rechnen.\n\nMindestens ein israelisches Schiff muss überleben.|Mission starten
Taskforce1Osasdestroyed-playervictoryMessage=SIEG|Sieg! Sämtliche ägyptischen Lenkwaffenschnellboote wurden zerstört. Gute Arbeit, Kommandant.|Mission beenden
Taskforce2Osasdestroyed-playervictoryMessage=<color=red>Mission fehlgeschlagen</color>|Alle unsere Kräfte wurden zerstört. Sie wurden besiegt.|Mission beenden
Taskforce1Playerdestroyed-playerdefeatMessage=NIEDERLAGE|Niederlage! Alle Ihre Schiffe wurden im Gefecht zerstört!|Mission beenden
Objective_DestroyEnemyMissileBoats=Feindliche Lenkwaffenschnellboote vernichten
Objective_OneShipMustSurvive=Mindestens ein eigenes Schiff muss überleben

[Language_cn]
Name=巴尔的姆之战（1973）
Description=赎罪日战争爆发三天后，以色列军队正全力与阿拉伯国家作战。你的导弹艇部队刚从拉塔基亚之战中得胜而归，已改道向西，支援以色列国防军向西奈半岛推进。前往塞得港，找到并摧毁此地区的埃及导弹艇舰队。
Taskforce1StartmessageMessage=<size=20>赎罪日战争——第2部分</size>\n巴尔的姆之战|赎罪日战争爆发三天后，以色列军队正全力与阿拉伯国家作战。你的导弹艇部队刚从拉塔基亚之战中得胜而归，已改道向西，支援以色列国防军向西奈半岛推进。\n\n侦察发现埃及的4艘205型导弹艇从亚历山大港向东移动，向西航行并摧毁它们。预计靠近海岸的位置会有大量民用船只通行。\n\n你至少有一艘船只不被击沉。|开始任务
Taskforce1Osasdestroyed-playervictoryMessage=任务完成！|任务完成！埃及导弹艇已被全部摧毁。干得好，指挥官！|退出任务
Taskforce2Osasdestroyed-playervictoryMessage=<color=red>任务失败！</color>|我军部队已损失殆尽，你失败了。
Taskforce1Playerdestroyed-playerdefeatMessage=任务失败！|你失败了！你的所有船只都在战斗中损失了！|退出任务
Objective_DestroyEnemyMissileBoats=摧毁敌方导弹艇
Objective_OneShipMustSurvive=你至少有一艘船只不被击沉

[Language_es]
Name=La Batalla de Baltim (1973)
Description=Durante la Batalla de Baltim se enfrentaron cara a cara la marina israelí y la armada egipcia en el contexto de la guerra del Yom Kippur. Comenzó con la incursión de seis lanchas patrulleras lanzamisiles israelíes clase Sa'ar que se dirigían a Puerto Saíd, saliendo al encuentro de las mismas cuatro barcos lanzamisiles egipcios de la clase Osa que provenían desde Alejandría.
Taskforce1StartmessageMessage=<size=40>La Batalla de Baltim</size>|¡Bienvenido Comandante!\n\n<size=15>En esta misión tu objetivo principal será encontrar y hundir a un grupo de <color=
Taskforce2StartmessageMessage=<size=40>La Batalla de Baltim</size>|¡Bienvenido Comandante!\n\n<size=15>En esta misión tu objetivo principal será encontrar y hundir a un grupo de <color=
Taskforce1Osasdestroyed-playervictoryMessage=<color=lime>¡Misión cumplida!</color>|¡Bien hecho Comandante! Las fuerzas enemigas han sido destruidas. ¡Buen trabajo!
Taskforce2Osasdestroyed-playervictoryMessage=<color=red>Misión fallida</color>|Todas nuestras fuerzas han sido destruidas. Hemos sido derrotados.
Taskforce1Playerdestroyed-playerdefeatMessage=<color=red>Misión fallida</color>|Todas nuestras fuerzas han sido destruidas. Hemos sido derrotados.
Taskforce2Playerdestroyed-playerdefeatMessage=<color=lime>¡Misión cumplida!</color>|¡Bien hecho Comandante! Las fuerzas enemigas han sido destruidas. ¡Buen trabajo!
[Language_fr]
Name=Battle of Baltim (1973)
[Language_ko]
Name=발팀 해전 (1973)
Description=욤 키푸르 전쟁이 시작된 지 사흘 만에 이스라엘 군대는 아랍 국가들에 맞서 치열한 전투를 벌이고 있습니다. 최근 라타키아 해전에서 승리하고 돌아온 사르급 미사일 고속정 부대가 IDF의 시나이 진격을 지원하기 위해 서쪽으로 재배치되었습니다. 사이드 항구로 이동한 다음 해당 지역에서 이집트 미사일 고속정 함대를 찾아 파괴하십시오.
Taskforce1StartmessageMessage=<size=20>욤 키푸르 전쟁 - 파트2</size>\\n발팀 해전|욤 키푸르 전쟁이 시작된 지 사흘 만에 이스라엘 군대는 아랍 국가들에 맞서 치열한 전투를 벌이고 있습니다. 최근 라타키아 해전에서 승리하고 돌아온 사르급 미사일 고속정 부대가 IDF의 시나이 진격을 지원하기 위해 서쪽으로 재배치되었습니다.\\n\\n정찰 결과 알렉산드리아에서 동쪽으로 이동하는 이집트 오사급 미사일 고속정 4척이 발견되었습니다. 서쪽으로 이동하여 그들을 파괴하십시오. 해안 근처에서는 민간 교통이 혼잡할 것으로 예상됩니다.\\n\\n최소한 한 척의 이스라엘 함선이 생존해야 합니다.|미션 시작
Taskforce1Osasdestroyed-playervictoryMessage=승리|승리! 당신은 모든 이집트군의 미사일 고속정을 격파했습니다. 수고하셨습니다, 사령관님.|미션 나가기
Taskforce2Osasdestroyed-playervictoryMessage="<color=red>미션 실패</color>|모든 아군이 전멸했습니다. 당신은 패배했습니다."
Taskforce1Playerdestroyed-playerdefeatMessage=패배|패배! 당신은 모든 함선을 잃었습니다!|미션 나가기
Objective_DestroyEnemyMissileBoats=적의 미사일 고속정 파괴
Objective_OneShipMustSurvive=적어도 한 척의 플레이어 함선은 반드시 살아남아야 함

[Environment]
Date=1973,10,8
Time=3,40
ConvertTimeToLocal=False
SeaState=4
Clouds=Broken
WindDirection=SE
MapCenterLatitude=32
MapCenterLongitude=31.05
LoadBackgroundData=True
[Mission]
Difficulty=4

#PlayerTaskforce=Taskforce2
#EnemyTaskforce=Taskforce1

PlayerTaskforce=Taskforce1
EnemyTaskforce=Taskforce2

Taskforce1_Nation=Israel
Taskforce2_Nation=Egypt

NumberOfTaskforce1Vessels=6
NumberOfTaskforce2Vessels=4
NumberOfNeutralVessels=5

NumberOfTriggers=4

[ ============================== Land Units ============================== ]
[ ---------- Taskforce1 ---------- ]
[ ---------- Taskforce2 ---------- ]
[ ----------   Neutral  ---------- ]
[ ================================ Vessels =============================== ]
[ ---------- Taskforce1 ---------- ]
[---------- North Group ----------]
[Taskforce1Vessel1] #INS Reshef
Type=ins_ptg_saar_4
VariantReference=Variant1
RelativePositionInNM=20,0,4
Heading=259
Telegraph=3
Waypoints=-20,0,-4

[Taskforce1Vessel2] #INS Keshet
Type=ins_ptg_saar_4
VariantReference=Variant2
RelativePositionInNM=21,0,3
Heading=259
Telegraph=3
Waypoints=-20,0,-5

[---------- Center Group ----------]
[Taskforce1Vessel3] #INS Eilat
Type=ins_ptg_saar_2
VariantReference=Variant4
RelativePositionInNM=25,0,-3
Heading=260
Telegraph=3
Waypoints=-20,0,-11

[Taskforce1Vessel4] #INS Misgav
Type=ins_ptg_saar_2
VariantReference=Variant3
RelativePositionInNM=24,0,-6
Heading=262
Telegraph=3
Waypoints=-20,0,-12

[---------- South Group ----------]
[Taskforce1Vessel5] #INS Herev
Type=ins_ptg_saar_3
VariantReference=Variant4
RelativePositionInNM=21,0,-12
Heading=259
Telegraph=3
Waypoints=-20,0,-20

[Taskforce1Vessel6] #INS Sufa
Type=ins_ptg_saar_3
VariantReference=Variant2
RelativePositionInNM=20,0,-13
Heading=-100
Telegraph=3
Waypoints=-20,0,-21

[ ---------- Taskforce2 ---------- ]
[Taskforce2Vessel1]
Type=wp_ptg_osa1
VariantReference=Variant136
RelativePositionInNM=-3,0,-17.5
Heading=90
Telegraph=3
Waypoints=11.55139,0,-17.26227|-33.37628,0,-18.58612

[Taskforce2Vessel2]
Type=wp_ptg_osa1
VariantReference=Variant137
RelativePositionInNM=-12,0,-12
Heading=90
Telegraph=3
Waypoints=7.65033,0,-12.03369|-33.4303,0,-14.51111

[Taskforce2Vessel3]
Type=wp_ptg_osa1
VariantReference=Variant138
RelativePositionInNM=-8,0,-15
Heading=90
Telegraph=3
Waypoints=9.583924,0,-14.6608|-33.48523,0,-16.57585

[Taskforce2Vessel4]
Type=wp_ptg_osa1
VariantReference=Variant135
RelativePositionInNM=-5,0,-20
Heading=90
Telegraph=3
Waypoints=20,0,-20
Waypoints=13.06476,0,-19.96628|-33.21332,0,-20.54214

[ ----------   Neutral  ---------- ]
[NeutralVessel1]
Type=civ_fv_fishingboat_a
VariantReference=Random
RelativePositionInNm=0,0,3
Heading=117
Telegraph=3
Waypoints=12,0,-3

[NeutralVessel2]
Type=civ_fv_fishingboat_a
VariantReference=Random
RelativePositionInNm=3,0,0
Heading=259
Telegraph=0
Waypoints=-12,0,-3

[NeutralVessel3]
Type=civ_fv_fishingboat_a
VariantReference=Random
RelativePositionInNm=0,0,-3
Heading=-90
Telegraph=0
Waypoints=-12,0,-3

[NeutralVessel4]
Type=civ_fv_fishingboat_a
VariantReference=Random
RelativePositionInNM=-3,0,0
Telegraph=0
Heading=270
Waypoints=-12,0,-3

[NeutralVessel5]
Type=civ_fv_fishingboat_a
VariantReference=Default
CrewSkill=Green
Stores=Depleted
RelativePositionInNM=8.95,0,-15.53
Telegraph=0
Heading=105
Waypoints=23.52191,0,-19.50485
[ ============================== Submarines ============================== ]
[ ---------- Taskforce1 ---------- ]
[ ---------- Taskforce2 ---------- ]
[ ----------   Neutral  ---------- ]
[ =============================== Aircraft =============================== ]
[ ---------- Taskforce1 ---------- ]
[ ---------- Taskforce2 ---------- ]
[ ----------   Neutral  ---------- ]
[ ============================== Helicopters ============================= ]
[ ---------- Taskforce1 ---------- ]
[ ---------- Taskforce2 ---------- ]
[ ----------   Neutral  ---------- ]
[ ============================== Triggers ============================= ]
[Trigger1]  #Mission exit
Name=Mission exit
Description=Trigger to end mission automaticaly
Disabled=True
Action_EndMission=True
Condition_Condition1_Type=Time
Condition_Condition1_Time=10
ConditionsCompleted=<Condition1>
[Trigger2]
Name=Start message
Description=Message displayed at the beginning of the mission
Action_Taskforce1_Message=Taskforce1StartmessageMessage
Action_Taskforce2_Message=Taskforce2StartmessageMessage
Condition_Condition1_Type=Time
Condition_Condition1_Time=5
ConditionsCompleted=<Condition1>
[Trigger3]
Name=Osas destroyed - player victory
Action_Taskforce1_Message=Taskforce1Osasdestroyed-playervictoryMessage
Action_Taskforce2_Message=Taskforce2Osasdestroyed-playervictoryMessage
Action_Victory=Taskforce1
Action_ObjectivesCompleted=DestroyEnemyMissileBoats,OneShipMustSurvive
Condition_Condition1_Type=HasNoUnitsOfType
Condition_Condition1_Taskforce=Taskforce2
Condition_Condition1_UnitType=Vessel
ConditionsCompleted=<Condition1>
[Trigger4]
Name=Player destroyed - player defeat
Action_Taskforce1_Message=Taskforce1Playerdestroyed-playerdefeatMessage
Action_Taskforce2_Message=Taskforce2Playerdestroyed-playerdefeatMessage
Action_Victory=Taskforce2
Action_ObjectivesFailed=DestroyEnemyMissileBoats,OneShipMustSurvive
Action_EnableTriggers=Trigger1
Condition_Condition1_Type=HasNoUnitsOfType
Condition_Condition1_Taskforce=Taskforce1
Condition_Condition1_UnitType=Vessel
ConditionsCompleted=<Condition1>
[Taskforce1_Objectives]
DestroyEnemyMissileBoats=20,-20,Complete,Main
OneShipMustSurvive=5,-5,Complete
[BackgroundData]
NumberOfBackgroundCityFiles=1
BackgroundCityFile1_Path=\campaigns\middleeast_cities.ini
BackgroundCityFile2_Path=\campaigns\cities.ini
NumberOfBackgroundAirportFiles=0
BackgroundAirportFile1_Path=\campaigns\airports.ini
BackgroundAirportFile1_DefaultGroupFile=\formations\New File.unitgroup
NumberOfBackgroundPortFiles=0
BackgroundPortFile1_Path=\campaigns\middle_east_ports.ini
BackgroundPortFile1_DefaultGroupFile=
NumberOfBackgroundInstallationFiles=0
NumberOfBackgroundSceneryFiles=0
